version: "3.7"
services:
  docker_app_service:
    build: .
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:12"
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: java_to_dev_app_db
      POSTGRES_PASSWORD: nE5kMc7JCGNqwDQM